---
title: "pulse_survey"
output: html_document
---

```{r setup, include=FALSE}



library(tidyverse)
library(usmap)
knitr::opts_chunk$set(fig.width=12, fig.height=8) 


pulse_survey <- read_csv("pulse2021_puf_24.csv")

pulse_weights <- read_csv("pulse2021_puf_24.csv")



```

## Some cleaning



```{r}
head(pulse_weights)


sum(pulse_weights$INCOME)




pulse_survey_weighted <- left_join(pulse_survey, pulse_weights, 
                                   by = c("SCRAM" = "SCRAM"))

head(pulse_survey_weighted)


exp_loss_subset <- pulse_survey_weighted %>% 
  dplyr::select(c(SCRAM, EST_ST.x, EXPCTLOSS.x, EXPCTLOSS.y))



head(exp_loss_subset)


pulse_weights$w_exp_loss <- pulse_weights$EXPCTLOSS * pulse_weights$PWEIGHT



exp_loss_subset <- pulse_weights %>% 
  dplyr::select(c(SCRAM, EST_ST, EXPCTLOSS, PWEIGHT))

# PWEIGHT == person weight, HWEIGHT == household weight

exp_loss_subset_oh <- exp_loss_subset %>% 
  filter(EST_ST == 39)





exp_loss_subset_oh %>% 
  group_by(EXPCTLOSS) %>% 
  summarise(weight = sum(PWEIGHT))



```





## Make the above a function

You can also embed plots, for example:

```{r}

f_pct <- function(state_function){
  st_filt <- pulse_weights %>% 
    filter(EST_ST == state_function)
  
  exp_l <- st_filt %>% 
    group_by(EXPCTLOSS) %>% 
    summarise(weight_func = sum(PWEIGHT))
  
  pct_calc <- exp_l$weight_func[2]/
  (exp_l$weight_func[1]+exp_l$weight_func[3]+exp_l$weight_func[2])

#  pcdf <- data.frame(state_function, pct_calc)
  return(pct_calc)
}

f_pct(20)

statevector <- sort(unique(pulse_weights$EST_ST))





statevector_df <- data.frame(as.numeric(statevector))

statevector_df <- statevector_df %>% 
  mutate(row_id = row_number())


state_list <- map(statevector, f_pct)



state_list_binded <- do.call("rbind", state_list)

state_list_binded <- as.data.frame(state_list_binded)

state_list_binded <- state_list_binded %>% 
  mutate(row_id = row_number())

final_df <- left_join(state_list_binded, statevector_df,
                      by = c("row_id" = "row_id"))

```



## Now easy map to build
```{r}

final_df$as.numeric.statevector.


final_df <- rename(final_df, FIPS=as.numeric.statevector.)

final_df <- rename(final_df, value = V1)

final_df <- final_df %>% 
  dplyr::select(c(value, FIPS))



final_df$FIPS <- as.character(final_df$FIPS )


final_df$FIPS[1] <- "01"
final_df$FIPS[2] <- "02"
final_df$FIPS[3] <- "04"
final_df$FIPS[4] <- "05"
final_df$FIPS[5] <- "06"
final_df$FIPS[6] <- "08"
final_df$FIPS[7] <- "09"

final_df <-  rename(final_df, fips=FIPS)

final_df <- final_df %>% 
  filter(fips != "11")


final_df <- final_df[,c(2, 1)]
  




ggplot(final_df, aes(x = reorder(fips, -value) , y = value)) +
  geom_col() +
  labs(x = "State FIPS Code", y = "% Who Expect Household Job Loss") +
  theme_minimal()



```




## Look at age breakdown of some question

```{r}

# filter dataset to only include people in between ages of 21 and 25

pulse_young <- pulse_weights %>%
  filter(TBIRTH_YEAR %in% (1996:2000))






# find % of people who did not do any work in past week


pct_young_work <-  pulse_young %>% 
  group_by(ANYWORK) %>% 
  summarise(weight = sum(PWEIGHT))


pct_young_work$weight[3] / 
    (pct_young_work$weight[1] + pct_young_work$weight[2] +  
     pct_young_work$weight[3])


# 38.8% of young people did not work in the past week
# filter out non substantive variables


pulse_young <- pulse_young %>% 
  filter(ANYWORK != -99)


pct_young_work_ms <- pulse_young %>% 
  filter(EST_ST == 28)




pct_young_work_ms <-  pct_young_work_ms %>% 
  group_by(ANYWORK) %>% 
  summarise(weight = sum(PWEIGHT))




```

```{r}


pct_young_not_working_function <- function(state_function_yp){
  st_filter <- pulse_young %>% 
    filter(EST_ST == state_function_yp)
  
  not_working <- st_filter %>% 
    group_by(ANYWORK) %>% 
    summarise(weight_work = sum(PWEIGHT))
  
  pct_calc_young <- not_working$weight_work[2]/
  (not_working$weight_work[1] + not_working$weight_work[2])

#  pcdf <- data.frame(state_function, pct_calc)
  return(pct_calc_young)
}

pct_young_not_working_function(38)



```

```{r}


statevector_youngemp <- sort(unique(pulse_weights$EST_ST))

statevector_youngemp_df <- as.data.frame(statevector_youngemp)

statevector_youngemp_df <- statevector_youngemp_df %>% 
  mutate(row_id = row_number())



young_employment_mapped <- map(statevector_youngemp, 
                                pct_young_not_working_function)





young_employment_binded <- do.call("rbind", young_employment_mapped)




young_employment_binded_df <- as.data.frame(young_employment_binded)



young_employment_binded_df <- young_employment_binded_df %>% 
  mutate(row_id = row_number())




final_young_employment <- left_join(young_employment_binded_df, 
                                    statevector_youngemp_df,
                                    by = c("row_id" = "row_id"))






```


```{r}

final_young_employment <- final_young_employment %>% 
  mutate(pct_not_working = round(V1 *100, 2))




fips_codes <- read_csv("state_fips_codes.csv")

fips_codes$fips <- as.character(fips_codes$fips)


fips_codes$fips[1] <- "01"
fips_codes$fips[2] <- "02"
fips_codes$fips[3] <- "04"
fips_codes$fips[4] <- "05"
fips_codes$fips[5] <- "06"
fips_codes$fips[6] <- "08"
fips_codes$fips[7] <- "09"




final_young_employment_add_fips <- left_join(final_young_employment,
                                             fips_codes, by = 
                                               c("statevector_youngemp" = 
                                                   "fips"))

final_young_employment_add_fips$code[9] <- "DC"





ggplot(final_young_employment_add_fips, aes(x = reorder(code, -pct_not_working), 
                                            y = pct_not_working,
                                            width = 0.5)) +
  labs(x = "State", y = "Percent not working", 
      title = "Young People who Responded that they Did not Work Last Week",
      caption = "Source: Census PULSE Survey, Feb. 3 - Feb. 15, 2021",
      subtitle = "Ages 21-25") +
  geom_col(fill = "blue") +
  theme_minimal()



```


